### PR TITLE
Add design kit to developer's guide

### PR DESCRIPTION
**Pull request by wteouchicago**
Adds style guide to developer's guide.

### CODE REVIEW

**Comment by wteouchicago** [comment]
@wwysoc2 - are you ok with adding the style PDF to a PDF subfolder?

**Review by wwysoc2 — APPROVED** [review]
lgtm, the only suggestion I would have is to replace the spaces in the file name with underscores.  If this presents any issues elsewhere, I'm okay not doing it.

**Comment by wteouchicago** [comment]
> lgtm, the only suggestion I would have is to replace the spaces in the file name with underscores. If this presents any issues elsewhere, I'm okay not doing it.

I was considering doing that, so I'll do that!

**Comment by wwysoc2** [comment]
> @wwysoc2 - are you ok with adding the style guide PDF to a PDF subfolder?

That's okay, but let me make sure the PDF folders aren't cleared out during doc site deployment (though we might be deploying in a different way after the doc site changes)

**Comment by wteouchicago** [comment]
> That's okay, but let me make sure the PDF folders aren't cleared out during doc site deployment (though we might be deploying in a different way after the doc site changes)

maybe if we name the PDF folder differently? e.g. "Style Guide PDF"?

**Comment by wwysoc2** [comment]
@wteouchicago I just checked and I don't think anything in the PDF folders gets cleared out, so that directory should work fine.

**Pull request merged**
