### PR TITLE
DOC-446 Remove links and mention of AWG Pre-Release Portal

### PR DESCRIPTION
**Pull request by bullenc**
[DOC-446](https://gdc-ctds.atlassian.net/browse/DOC-446)

### CODE REVIEW

**Comment by wteouchicago** [comment]
Do we want to remove the Pre_Release_QC.md file too?

**Comment by bullenc** [comment]
> Do we want to remove the Pre_Release_QC.md file too?

@wteouchicago I was going off of the precedent by where Portal V1 docs still exist in the repo, and we have just removed the links. I am fine with removing the docs since it's only page too.

**Comment by wteouchicago** [comment]
> @wteouchicago I was going off of the precedent by where Portal V1 docs still exist in the repo, and we have just removed the links. I am fine with removing the docs since it's only page too.

Fine by me either way -- whatever is normal practice.

**Review by wteouchicago — APPROVED** [review]

**Comment by bullenc** [comment]
changes merged in DR41 release notes

**Pull request closed without merging**
